baseURL: https://MilesChing.github.io/
title: MilesChing
author: Zhengrui Qin
copyright: >-
  Copyright © 2020, MilesChing (Zhengrui Qin); all rights
  reserved.
paginate: 5
languageCode: en
DefaultContentLanguage: en
enableInlineShortcodes: true
theme: milesching-paper-mod

params:
  description: 'Blog of Zhengrui Qin'
  author: Zhengrui Qin
  ShowReadingTime: true
  contentTypeName: posts
  defaultTheme: auto
  ShowShareButtons: true
  showToc: true
  tocOpen: true
  # profileMode:
  #   enabled: false
  #   title: PaperMod
  #   imageUrl: '#'
  #   imageTitle: my image
  #   buttons:
  #     - name: Archives
  #       url: archives
  #     - name: Tags
  #       url: tags

  homeInfoParams:
    Title: "MilesChing (Zhengrui Qin)"
    Content: Hi there. Welcome to my blog :)

  socialIcons:
    # - name: twitter
    #   url: '#'
    # - name: stackoverflow
    #   url: '#'
    # - name: codepen
    #   url: '#'
    # - name: linkedin
    #   url: '#'
    # - name: github
    #   url: 'https://github.com/adityatelange/hugo-PaperMod'

markup:
  tableOfContents:
    endLevel: 3
    ordered: false
    startLevel: 1

menu:
  main:
    - name: Posts
      url: /posts/
      weight: 5
    - name: Tags
      url: /tags/
      weight: 10

taxonomies:
  category: categories
  tag: tags

privacy:
  vimeo:
    disabled: false
    simple: true

  twitter:
    disabled: false
    enableDNT: true
    simple: true

  instagram:
    disabled: false
    simple: true

  youtube:
    disabled: false
    privacyEnhanced: true

services:
  instagram:
    disableInlineCSS: true
  twitter:
    disableInlineCSS: true

markup:
  defaultMarkdownHandler: goldmark
  goldmark:
    renderer:
      unsafe: true